Add bookings
Almor47/java-shareit pull request #4
Opened 2023-06-25 09:42 UTC by Almor47

2023-06-26 14:39 UTC, sergeymamonov requested changes

2023-06-26 14:39 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (state.equals(State.ALL.name())) {
Метод equals необходимо вызывать у константы или у значения, которое гарантированно не равно null. Потому что если значение, у которого вызывается метод equals будет равно null, то получим NPE. Поправить во всех аналогичных случаях.

2023-06-26 14:39 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                            itemService.getItemByIdRepository(booking.getItemId())))
Не очень хорошо делать запросы к БД в цикле. Это большая нагрузка на БД. Затратно по времени из-за передачи по сети. Исправить во всех аналогичных случаях.

2023-06-26 14:39 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/exception/WrongState.java
> +public class WrongState extends RuntimeException {
Обычно все классы ошибок оканчиваются на Exception.

2023-06-26 14:39 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    /*@ManyToOne(fetch = FetchType.LAZY)
В проекте не должно быть закомментированного кода.

2023-06-26 14:39 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        //return itemRepository.findAllByOwner(userId);
Закомментированный код.

2023-06-26 14:39 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            User user = userService.getUserById(one.getAuthorId());
Запросы к БД в цикле.

2023-06-26 14:39 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +/*@Entity
Закомментированный код.

2023-06-27 20:53 UTC, sergeymamonov requested changes

2023-06-27 20:53 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        userService.getUserById(booking.getBookerId()), booking.getItem()))
Запросы к БД в цикле.

2023-06-27 20:53 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/exception/BadRequestComment.java
> +public class BadRequestComment extends RuntimeException {
...Exception

2023-06-27 20:53 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Booking last = bookingRepository.findLastBooking(itemId, LocalDateTime.now()).stream().findFirst().orElse(null);
Запросы к БД в цикле.

2023-06-27 20:53 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            List<CommentDto> commentsDto = listCommentToListCommentDto(itemId);
В этом методе выполняются запросы к БД, а значит запросы к БД выполняются в цикле.

2023-06-28 04:14 UTC, Almor47 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Booking last = bookingRepository.findLastBooking(itemId, LocalDateTime.now()).stream().findFirst().orElse(null);
Не очень понимаю как сделать тогда. Выше метод public ItemDto getItemById(Long itemId, Long userId). Там я нахожу предмет, потом отдельным запросом: комментарии, последнее и следующее бронирование и с помощью Mapper собираю ответ.  
public List<ItemDto> getUserItem(Long userId), а почему тут плохо найти List<Item> и для каждого Item  по сути вызывать getItemById. 
через аннотацию @ManyToOne комментарии к Item добавить можно и тогда они будут выгружаться сразу, а что делать с первым и последним бронированием?

2023-06-28 13:30 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Booking last = bookingRepository.findLastBooking(itemId, LocalDateTime.now()).stream().findFirst().orElse(null);
Выгрузите из БД все бронирования для всех вещей из itemList (это 1 запрос). И уже на стороне приложения для каждой вещи найдите нужные бронирования. Можно сложить например в мапу (вещь - нужное бронирование). И потом из мапы доставать за константное время нужное бронирование.

2023-06-28 13:44 UTC, Almor47 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Booking last = bookingRepository.findLastBooking(itemId, LocalDateTime.now()).stream().findFirst().orElse(null);
Я правильно понял что нужно пошагово (для метода где нужно получить все вещи пользователя)
1. выгружаю все вещи
2. через букингрепозитори выгружаю лист Букингов, где айти итема In()
3. на стороне приложения из этого листа формирую Map, где по ключу айди итема будут лежать все букинги.
4. в цикле надо перебирать все букинги и искать по if - условиям LastBooking и NextBooking
5. и мапить результат

2023-06-28 13:51 UTC, Almor47 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Booking last = bookingRepository.findLastBooking(itemId, LocalDateTime.now()).stream().findFirst().orElse(null);
Настолько лохи циклические запросы? просто по этому алгоритму как минимум +1 действие перекладывание из листа в мапу + создание List<> с айдиВыгруженных итемов

2023-06-28 14:33 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Booking last = bookingRepository.findLastBooking(itemId, LocalDateTime.now()).stream().findFirst().orElse(null);
Создание одного листа и проход по нему с созданием мапы - эти операции вы ожидаете, то есть знаете количество. Листов и мап в программе создается много) А вот количество запросов к БД вы не можете сейчас оценить. Их может быть и 10, а может 10_000 или более. Допустим, запрос по сети к БД это сотые доли секунды. У вас последовательно выполняются запросы, то есть один этот цикл может выполняться секунду(секунды).

2023-06-28 14:36 UTC, Almor47 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Booking last = bookingRepository.findLastBooking(itemId, LocalDateTime.now()).stream().findFirst().orElse(null);
понял, спасибо за объяснения

2023-06-29 04:30 UTC, sergeymamonov commented
Если вы по запросы в цикле называет "Исправление циклических зависимостей", то это разные вещи. Можете посмотреть в интернете, что такое циклические зависимости, если еще не сталкивались с этим.

2023-06-29 04:40 UTC, sergeymamonov approved these changes

2023-06-29 16:07 UTC, merged